//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gn_service_asst
    {
        public int srvasst_id { get; set; }
        public string srvasst_code { get; set; }
        public string srvasst_name { get; set; }
    }
}
